config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admin do

    resources :homes, :only => [:index]

    resources :products, :only => [:index, :new, :edit, :create, :update, :destroy] do
      patch :toggle_statuss
    end
    get 'products/:gender' => 'products#show', as: 'products_show'

    resources :arts, :only => [:index, :new, :edit, :create, :update, :destroy]

    resources :genres, :only => [:show]

  	resources :snaps, :only => [:index, :new, :edit, :create, :update, :destroy] do
  		resources :items, :only => [:create, :update, :destroy]
      resources :snap_images, :only => [:create, :update, :destroy]
  	end
  end

  resources :homes, :only => [:index]

  resources :abouts, :only => [:index]

  resources :products, :only => [:index]
  get 'products/:gender' => 'products#show', as: 'products_show'

  resources :snaps, :only => [:index]

  resources :delis, :only => [:index]

  resources :genres, :only => [:show]

  resources :arts, :only => [:index]

 	get 'contacts' => 'contacts#index'
	post 'contacts/confirm' => 'contacts#confirm'
	post 'contacts/thanks' => 'contacts#thanks'

	root 'homes#index'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/art.rb
class Art < ApplicationRecord

	extend Refile::Attachment
	attr_accessor :art_image_id
	has_many :art_images, inverse_of: :art, dependent: :destroy
	accepts_attachments_for :art_images, attachment: :image

	validates :event_name, presence: true
	validates :artist_name, presence: true
	validates :start_date, presence: true
	validates :end_date, presence: true
	validates :event_info, presence: true
end

app/models/art_image.rb
class ArtImage < ApplicationRecord
	belongs_to :art, optional: true, inverse_of: :art_images
	attachment :image
end

app/models/contact.rb
class Contact < include ActiveModel::Model
 
  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/deli.rb
class Deli < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, inverse_of: :genre
	accepts_nested_attributes_for :items, allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre , optional: true, inverse_of: :items
	belongs_to :snap , optional: true, inverse_of: :items

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_images, dependent: :destroy
	accepts_attachments_for :product_images, attachment: :image

	enum statuss: { 販売中: 0, SOLDOUT: 1 }

	scope :get_by_gender, ->(gender) {
	where(gender: gender)
	}

	validates :product_name, presence: true
	validates :price, presence: true
	validates :gender, presence: true
	validates :size, presence: true

  def toggle_statuss!
    if 販売中?
      SOLDOUT!
    else
      販売中!
    end
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
	belongs_to :product
	attachment :image
end

app/models/snap.rb
class Snap < ApplicationRecord
	 attr_accessor :genre_id
	 attr_accessor :item_name
	has_many :items, inverse_of: :snap, dependent: :destroy
        accepts_nested_attributes_for :items, allow_destroy: true

	extend Refile::Attachment
	attr_accessor :snap_image_id
	has_many :snap_images, inverse_of: :snap, dependent: :destroy
	accepts_attachments_for :snap_images, attachment: :image

end

app/models/snap_image.rb
class SnapImage < ApplicationRecord
	belongs_to :snap, optional: true, inverse_of: :snap_images
	attachment :image
end

app/controllers/admin/snaps_controller.rb
class Admin::SnapsController < ApplicationController

	layout 'application.html 2'
	before_action :authenticate_admin!
	before_action :params_snap, only:[:index, :update, :create, :edit, :destroy]

	def index
		@snaps = Snap.all.reverse_order
	end

	def update
    	if @snap.update(snap_params)
    		redirect_to admin_snaps_path
    	else
    		render :edit
    	end
	end

	def edit
	end

	def new
		@snap = Snap.new
                @snap.items.build
		@snap.snap_images.build
	end

	def create
		@snap = Snap.new(snap_params)

		if @snap.save
			redirect_to admin_snaps_path
		else
			render :new
		end
	end

	def destroy
		@snap.destroy
		redirect_to admin_snaps_path
 	end

	private

	def params_snap
		@snap = Snap.find_by(id: params[:id])
	end

	def snap_params
	  params.require(:snap).permit(:id, :snap_name, { items_attributes: [:id, :item_name, :genre_id, :_destroy, { genres_attributes: [:id, :genre_name, :_destroy] }] }, snap_images_images: [])
	end
end

app/controllers/snaps_controller.rb
class SnapsController < ApplicationController
	def index
		@snaps = Snap.all.reverse_order
	end

	private

	def snap_params
	  params.require(:snap).permit(:id, :snap_name, { items_attributes: [:id, :item_name, :_destroy, { genres_attributes: [:id, :genre_name, :_destroy] }] }, snap_images_images: [])
	end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/snaps_helper.rb
module Admin::SnapsHelper
	def link_to_add_field(name, f, association, options={})
		new_object = f.object.class.reflect_on_association(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
			render(association.to_s.singularize + "_form", f: builder)
		end
		link_to(name, '', class: "add_field", data: {id: id, fields: fields.gsub("\n","")})
	end
	def link_to_remove_field(name, f, options={})

		f.hidden_field(:_destroy) + link_to(name, '#', class: "remove_field")
	end
end

app/helpers/artimages_helper.rb
module ArtimagesHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/delis_helper.rb
module DelisHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/snapimages_helper.rb
module SnapimagesHelper
end

app/helpers/snaps_helper.rb
module SnapsHelper
end

app/views/admin/snaps/_form.html.erb
<div class="form-group">
	<label class="col-sm-2 control-label" for="InputText">Snap Item</label>
	<div class="col-sm-10">
		<%= f.fields_for :items do |b| %>
			<%= b.collection_select :genre_id, Genre.all, :id, :genre_name, {}, {:class => "form-control genre-area", :style =>"width: 200px; display: inline-block; margin: 5px 0 0 30px;"} %>
			<%= b.text_field :item_name, id: "InputText", class: "form-control input-sm itemname", style:"width: 400px; display: inline-block; margin: 5px 0 0 5px;", placeholder:"Item Name" %>
			<%= b.hidden_field :id %>
		<% end %></br>
		<%= link_to_add_field("Add Item", f, :items, {}) %>
	</div>
</div>

app/views/admin/snaps/_item_form.html.erb
<div>
	<%= f.collection_select :genre_id, Genre.all, :id, :genre_name, {}, {:class => "form-control genre-area", :style =>"width: 200px; display: inline-block; margin: 5px 0 0 30px;"} %>
	<%= f.text_field :item_name, id: "InputText", class: "form-control input-sm itemname", style:"width: 400px; display: inline-block; margin: 5px 0 0 5px;", placeholder:"Item Name" %>
	<%= f.hidden_field :id %>

	<%= link_to_remove_field("Delete", f, {}) %>
</div>

app/views/admin/snaps/edit.html.erb
<div class="panel panel-default container", style="margin-top: 70px;" >
	<div class="panel-body" >
		<%= form_for(@snap, url: admin_snaps_path, html: {class: 'form-horizontal'}) do |f| %>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Snap Name</label>
				<div class="col-sm-10">
					<%= f.text_field :snap_name, id:"InputText", class:"form-control", placeholder:"スナップ名を入力して下さい。" %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputFile">Snap Image</label>
				<div class="col-sm-10">
					<%= f.attachment_field :snap_images_images, id:"InputFile", multiple: true %>
				</div>
			</div>
			<%= f.hidden_field :id %>
				<%= render partial: 'admin/snaps/form', locals: {f: f } %>
			<%= f.submit '編集する', class:"btn btn-primary center-block" %>
		<% end %>
	</div>
	<div class="panel-footer" >
	</div>
</div>

app/views/admin/snaps/index.html.erb
<div class="section-content">
	<div class="section-main2">
		<div class="snapshot-list">
			<ul>
				<% @snaps.each do |snap| %>
				<li class="box-number2">
					<div class="snapshot-inner">
						<div>
							<ul class="snapshotimage">
							<% snap.snap_images.each do |image| %>
   								<% if image.image_id.present? %>
									<%= attachment_image_tag image, :image %>
								<% end %>
							<% end %>


							</ul>
						</div>
						<table class="snapinfo">
							<th class="snapname"><%= snap.snap_name %></th>
							<% snap.items.each do |item| %>
							<tr>
								<td class="genre"><%= item.genre.try(:genre_name) %></td>
								<td class="snapitem"><%= item.item_name %></td>
							</tr>
							<% end %>
						</table>
						<%#= link_to "編集", edit_admin_snap_path(snap), class:"btn btn-primary btn-xs" %>
						<%= link_to "削除", admin_snap_path(snap), method: :delete, class:"btn btn-danger btn-xs", "data-confirm" => "本当に削除しますか？" %>
					</div>
				</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/admin/snaps/new.html.erb
<div class="panel panel-default container", style="margin-top: 70px;" >
	<div class="panel-body" >
		<%= form_for(@snap, url: admin_snaps_path, html: {class: 'form-horizontal'}) do |f| %>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Snap Name</label>
				<div class="col-sm-10">
					<%= f.text_field :snap_name, id:"InputText", class:"form-control", placeholder:"スナップ名を入力して下さい。" %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputFile">Snap Image</label>
				<div class="col-sm-10">
					<%= f.attachment_field :snap_images_images, multiple: true %>
				</div>
			</div>
			<%= f.hidden_field :id %>
				<%= render partial: 'admin/snaps/form', locals: {f: f } %>
			<%= f.submit '作成する', class:"btn btn-primary center-block" %>
		<% end %>
	</div>
	<div class="panel-footer" >
	</div>
</div>