config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admin do

    resources :homes, :only => [:index]

    resources :products, :only => [:index, :new, :edit, :create, :update, :destroy] do
      patch :toggle_statuss
    end
    get 'products/:gender' => 'products#show', as: 'products_show'

    resources :arts, :only => [:index, :new, :edit, :create, :update, :destroy]

    resources :genres, :only => [:show]

  	resources :snaps, :only => [:index, :new, :edit, :create, :update, :destroy] do
  		resources :items, :only => [:create, :update, :destroy]
      resources :snap_images, :only => [:create, :update, :destroy]
  	end
  end

  resources :homes, :only => [:index]

  resources :abouts, :only => [:index]

  resources :products, :only => [:index]
  get 'products/:gender' => 'products#show', as: 'products_show'

  resources :snaps, :only => [:index]

  resources :delis, :only => [:index]

  resources :genres, :only => [:show]

  resources :arts, :only => [:index]

 	get 'contacts' => 'contacts#index'
	post 'contacts/confirm' => 'contacts#confirm'
	post 'contacts/thanks' => 'contacts#thanks'

	root 'homes#index'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/art.rb
class Art < ApplicationRecord

	extend Refile::Attachment
	attr_accessor :art_image_id
	has_many :art_images, inverse_of: :art, dependent: :destroy
	accepts_attachments_for :art_images, attachment: :image

	validates :event_name, presence: true
	validates :artist_name, presence: true
	validates :start_date, presence: true
	validates :end_date, presence: true
	validates :event_info, presence: true
end

app/models/art_image.rb
class ArtImage < ApplicationRecord
	belongs_to :art, optional: true, inverse_of: :art_images
	attachment :image
end

app/models/contact.rb
class Contact < include ActiveModel::Model
 
  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/deli.rb
class Deli < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, inverse_of: :genre
	accepts_nested_attributes_for :items, allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre , optional: true, inverse_of: :items
	belongs_to :snap , optional: true, inverse_of: :items

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_images, dependent: :destroy
	accepts_attachments_for :product_images, attachment: :image

	enum statuss: { 販売中: 0, SOLDOUT: 1 }

	scope :get_by_gender, ->(gender) {
	where(gender: gender)
	}

	validates :product_name, presence: true
	validates :price, presence: true
	validates :gender, presence: true
	validates :size, presence: true

  def toggle_statuss!
    if 販売中?
      SOLDOUT!
    else
      販売中!
    end
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
	belongs_to :product
	attachment :image
end

app/models/snap.rb
class Snap < ApplicationRecord
	 attr_accessor :genre_id
	 attr_accessor :item_name
	has_many :items, inverse_of: :snap, dependent: :destroy
        accepts_nested_attributes_for :items, allow_destroy: true

	extend Refile::Attachment
	attr_accessor :snap_image_id
	has_many :snap_images, inverse_of: :snap, dependent: :destroy
	accepts_attachments_for :snap_images, attachment: :image

end

app/models/snap_image.rb
class SnapImage < ApplicationRecord
	belongs_to :snap, optional: true, inverse_of: :snap_images
	attachment :image
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

	layout 'application.html 2'
	before_action :authenticate_admin!
	before_action :params_product, only:[:index, :update,  :edit, :destroy]

	def index
		@products = Product.all.reverse_order
		@gender = Product.where('gender = ?', params[:gender])
	end

	def show
		@products = Product.where('gender = ?', params[:gender]).reverse_order
		@gender = Product.where('gender = ?', params[:gender])
	end

	def update
    	if @product.update(product_params)
    		redirect_to admin_products_path
    	else
    		render :edit
    	end
	end

	def edit
	end

	def new
		@product = Product.new
		@product.product_images.build
	end

	def create
		@product = Product.new(product_params)
		@product.product_images.build
		if @product.save
			redirect_to admin_products_path
		else
			render :new
		end
	end

	def destroy
		@product.destroy
		redirect_to admin_products_path
 	end

 	def toggle_statuss
 		@product = Product.find_by(id: params[:product_id])
		@product.toggle_statuss!
		redirect_to admin_products_path
	end

	private

	def params_product
		@product = Product.find_by(id: params[:id])
	end

	def product_params
	  params.require(:product).permit(:id, :product_name, :price, :gender, :size, :statuss, product_images_images: [])
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all.reverse_order
		@gender = Product.where('gender = ?', params[:gender])
	end

	def show
		@products = Product.where('gender = ?', params[:gender]).reverse_order
		@gender = Product.where('gender = ?', params[:gender])
	end

	private

	def product_params
	  params.require(:product).permit(:id, :product_name, :price, :gender, :size, :statuss, product_images_images: [])
	end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/artimages_helper.rb
module ArtimagesHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/delis_helper.rb
module DelisHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/snapimages_helper.rb
module SnapimagesHelper
end

app/helpers/snaps_helper.rb
module SnapsHelper
end

app/views/admin/products/edit.html.erb
<div class="panel panel-default container", style="margin-top: 70px;" >
	<div class="panel-body" >
		<%= form_for(@product, url: admin_product_path, html: {class: 'form-horizontal'}) do |f| %>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Product Name</label>
				<div class="col-sm-10">
					<%= f.text_field :product_name, id:"InputText", class:"form-control", placeholder:"商品名を入力して下さい。" %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputSelect">Gender</label>
				<div class="col-sm-10">
					<%= f.select :gender, ['Ladys', 'Mens', 'Unisex'], {include_blank: '選択して下さい'}, class: 'form-control gender-area' %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Size</label>
				<div class="col-sm-10">
					<%= f.text_field :size, id:"InputText", class:"form-control", placeholder:"サイズを入力して下さい" %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Price</label>
				<div class="col-sm-2">
					<div class="input-group">
						<span class="input-group-addon">￥</span>
						<%= f.number_field :price, class:"form-control input-sm" %>
					</div>
				</div>
				<p class="form-control-static">(半角数字)</p>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputFile">Product Image</label>
				<div class="col-sm-10">
					<%= f.attachment_field :product_images_images, id:"InputFile", multiple: true %>
				</div>
			</div>
			<%= f.submit '編集する', class:"btn btn-primary center-block" %>
		<% end %>
	</div>
	<div class="panel-footer" >
	</div>
</div>

app/views/admin/products/index.html.erb
<div class="section-content">
			<div class="section-main2">
				<div class="product-list">
			<ul>
				<% @products.each do |product| %>
					<li class="box-number2">
						<div class="product-inner">
								<ul class="productimage">
									<% product.product_images.each do |image| %>
										<%= attachment_image_tag image, :image %>
									<% end %>
								</ul>
							<div class="name">
								<p>
									<span><%= product.gender %>(<%= product.size %>)</span>
									<%= product.product_name %>
								</p>
							</div>
							<p class="priceen">¥<%= product.price %>+tax
							<span><%= product.statuss %></span></p>
						</div>
						<%= link_to "編集", edit_admin_product_path(product), class:"btn btn-primary btn-xs" %>
						<%= link_to "削除", admin_product_path(product), method: :delete, class:"btn btn-danger btn-xs", "data-confirm" => "本当に削除しますか？" %>
						<%= link_to product.statuss, admin_product_toggle_statuss_path(product), method: :patch, class:"btn btn-warning btn-xs" %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/admin/products/new.html.erb
<div class="panel panel-default container", style="margin-top: 70px;" >
	<div class="panel-body" >
		<%= form_for(@product, url: admin_products_path, html: {class: 'form-horizontal'}) do |f| %>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Product Name</label>
				<div class="col-sm-10">
					<%= f.text_field :product_name, id:"InputText", class:"form-control", placeholder:"商品名を入力して下さい。" %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputSelect">Gender</label>
				<div class="col-sm-10">
					<%= f.select :gender, ['Ladys', 'Mens', 'Unisex'], {include_blank: '選択して下さい'}, class: 'form-control gender-area' %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Size</label>
				<div class="col-sm-10">
					<%= f.text_field :size, id:"InputText", class:"form-control", placeholder:"サイズを入力して下さい" %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Price</label>
				<div class="col-sm-2">
					<div class="input-group">
						<span class="input-group-addon">￥</span>
						<%= f.number_field :price, class:"form-control input-sm" %>
					</div>
				</div>
				<p class="form-control-static">(半角数字)</p>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputFile">Product Image</label>
				<div class="col-sm-10">
					<%= f.attachment_field :product_images_images, id:"InputFile", multiple: true %>
				</div>
			</div>
			<%= f.submit '作成する', class:"btn btn-primary center-block" %>
		<% end %>
	</div>
	<div class="panel-footer" >
	</div>
</div>

app/views/admin/products/show.html.erb
<div class="section-content">
			<div class="section-main2">
			<div style="text-align: center">
				<%= link_to "ALL", admin_products_path, class: "genderlist" %>
				<%= link_to "LADY'S", admin_products_show_path(@gender, gender: 'Ladys'), class: "genderlist" %>
				<%= link_to "MEN'S", admin_products_show_path(@gender, gender: 'Mens'), class: "genderlist" %>
				<%= link_to "UNISEX", admin_products_show_path(@gender, gender: 'Unisex'), class: "genderlist" %>
			</div>
			<div class="product-list">
			<ul>
				<% @products.each do |product| %>
					<li class="box-number2">
						<div class="product-inner">
								<ul class="productimage">
									<% product.product_images.each do |image| %>
										<%= attachment_image_tag image, :image %>
									<% end %>
								</ul>
							<div class="name">
								<p>
									<span><%= product.gender %>(<%= product.size %>)</span>
									<%= product.product_name %>
								</p>
							</div>
							<p class="priceen">¥<%= product.price %>+tax
							<span><%= product.statuss %></span></p>
						</div>
						<%= link_to "編集", edit_admin_product_path(product), class:"btn btn-primary btn-xs" %>
						<%= link_to "削除", admin_product_path(product), method: :delete, class:"btn btn-danger btn-xs", "data-confirm" => "本当に削除しますか？" %>
						<%= link_to product.statuss, admin_product_toggle_statuss_path(product), method: :patch, class:"btn btn-warning btn-xs" %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/products/index.html.erb
<section id="home" class="home open">
	<p class="outline-title">MAMETRA</p>
</section>
<section id="used&clothing" class="used&clothing open active">
	<%= link_to products_path, style: "color: #fff;" do %>
	<h1>CLOTHES & SNAP</h1>
	<% end %>
	<div class="section-content">
		<div class="section-main">
			<div class="section-sec">
				<h2>CLOTHES</h2>
				<%= image_tag "used_clothing.jpg" %>
			</div>
			<div class="section-sec">
				<h2>SNAP</h2>
				<%= image_tag "snap_shot.jpg" %>
			</div>
		</div>
	</div>
</section>
<section id="deli&cafe" class="deli&cafe">
	<%= link_to delis_path do %>
	<h1>DELI CAFE</h1>
	<% end %>
	<div class="section-content">
	</div>
</section>
<section id="artspace" class="artspace">
	<%= link_to arts_path do %>
	<h1>ART SPACE</h1>
	<% end %>
	<div class="section-content">
	</div>
</section>

app/views/products/show.html.erb
<section id="home" class="home open">
	<p class="outline-title">MAMETRA</p>
</section>
<section id="used&clothing" class="used&clothing open active">
	<%= link_to products_path, style: "color: #fff;" do %>
	<h1>CLOTHES & SNAP</h1>
	<% end %>
	<div class="section-content">
		<div class="section-main">
		<h2>USED CLOTHING</h2>
		<div id="nav-bar">
			<ul class="nav">
				<%= link_to "ALL", products_path, class: "genderlist" %>
				<%= link_to "LADY'S", products_show_path(@gender, gender: 'Ladys'), class: "genderlist" %>
				<%= link_to "MEN'S", products_show_path(@gender, gender: 'Mens'), class: "genderlist" %>
				<%= link_to "UNISEX", products_show_path(@gender, gender: 'Unisex'), class: "genderlist" %>
				<%= link_to "SNAP SHOT", snaps_path, class: "genderlist" %>
			</ul>
		</div>
		<div class="product-list">
			<ul>
				<% @products.each do |product| %>
					<li class="box-number">
						<div class="product-inner">
							<div>
								<ul class="productimage">
									<% product.product_images.each do |image| %>
										<%= attachment_image_tag image, :image%>
									<% end %>
								</ul>
							</div>
							<div class="name">
								<p>
									<span><%= product.gender %>(<%= product.size %>)</span>
									<%= product.product_name %>
								</p>
							</div>
							<p class="priceen">¥<%= product.price %>+tax
							<span><%= product.statuss %></span></p>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
	</div>
</section>
<section id="deli&cafe" class="deli&cafe">
	<%= link_to delis_path do %>
	<h1>DELI CAFE</h1>
	<% end %>
	<div class="section-content">
	</div>
</section>
<section id="artspace" class="artspace">
	<%= link_to arts_path do %>
	<h1>ART SPACE</h1>
	<% end %>
	<div class="section-content">
	</div>
</section>