config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admin do

    resources :homes, :only => [:index]

    resources :products, :only => [:index, :new, :edit, :create, :update, :destroy] do
      patch :toggle_statuss
    end
    get 'products/:gender' => 'products#show', as: 'products_show'

    resources :arts, :only => [:index, :new, :edit, :create, :update, :destroy]

    resources :genres, :only => [:show]

  	resources :snaps, :only => [:index, :new, :edit, :create, :update, :destroy] do
  		resources :items, :only => [:create, :update, :destroy]
      resources :snap_images, :only => [:create, :update, :destroy]
  	end
  end

  resources :homes, :only => [:index]

  resources :abouts, :only => [:index]

  resources :products, :only => [:index]
  get 'products/:gender' => 'products#show', as: 'products_show'

  resources :snaps, :only => [:index]

  resources :delis, :only => [:index]

  resources :genres, :only => [:show]

  resources :arts, :only => [:index]

 	get 'contacts' => 'contacts#index'
	post 'contacts/confirm' => 'contacts#confirm'
	post 'contacts/thanks' => 'contacts#thanks'

	root 'homes#index'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/art.rb
class Art < ApplicationRecord

	extend Refile::Attachment
	attr_accessor :art_image_id
	has_many :art_images, inverse_of: :art, dependent: :destroy
	accepts_attachments_for :art_images, attachment: :image

	validates :event_name, presence: true
	validates :artist_name, presence: true
	validates :start_date, presence: true
	validates :end_date, presence: true
	validates :event_info, presence: true
end

app/models/art_image.rb
class ArtImage < ApplicationRecord
	belongs_to :art, optional: true, inverse_of: :art_images
	attachment :image
end

app/models/contact.rb
class Contact < include ActiveModel::Model
 
  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/deli.rb
class Deli < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, inverse_of: :genre
	accepts_nested_attributes_for :items, allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre , optional: true, inverse_of: :items
	belongs_to :snap , optional: true, inverse_of: :items

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_images, dependent: :destroy
	accepts_attachments_for :product_images, attachment: :image

	enum statuss: { 販売中: 0, SOLDOUT: 1 }

	scope :get_by_gender, ->(gender) {
	where(gender: gender)
	}

	validates :product_name, presence: true
	validates :price, presence: true
	validates :gender, presence: true
	validates :size, presence: true

  def toggle_statuss!
    if 販売中?
      SOLDOUT!
    else
      販売中!
    end
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
	belongs_to :product
	attachment :image
end

app/models/snap.rb
class Snap < ApplicationRecord
	 attr_accessor :genre_id
	 attr_accessor :item_name
	has_many :items, inverse_of: :snap, dependent: :destroy
        accepts_nested_attributes_for :items, allow_destroy: true

	extend Refile::Attachment
	attr_accessor :snap_image_id
	has_many :snap_images, inverse_of: :snap, dependent: :destroy
	accepts_attachments_for :snap_images, attachment: :image

end

app/models/snap_image.rb
class SnapImage < ApplicationRecord
	belongs_to :snap, optional: true, inverse_of: :snap_images
	attachment :image
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/delis_helper.rb
module DelisHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/snaps_helper.rb
module SnapsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html 2.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mametra</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
	<!-- /header -->
	<header id="top-header2">
	<div class="social">
			<%= link_to "COMMON", root_path, :target=>["_blank"] %>
			<%= link_to 'LOGOUT', destroy_admin_session_path, method: :delete %>
			<div>
				<p>SNAP →</p>
				<%= link_to "New", new_admin_snap_path %>
				<%= link_to "List", admin_snaps_path %>
			</div>
			<div>
				<p>ART →</p>
				<%= link_to "New", new_admin_art_path %>
				<%= link_to "List", admin_arts_path %>
			</div>
	</div>
		<%= link_to admin_homes_path do %>
			<%= image_tag 'mametra_logo.jpg', class: "logo" %>
		<% end %>
	</header>
	<!-- /header -->

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mametra</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
	<meta property="og:title" content="Mametra" />
	<meta property="og:type" content="website" />
	<meta property="og:description" content="ページの簡単な説明" />
	<meta property="og:url" content="ページのURL" />
	<meta property="og:site_name" content="サイトのタイトル" />
	<meta property="og:image" content="サムネイル画像のURL" />
  </head>

  <body>
	<!-- /header -->
	<header id="top-header">
		<div class="about-top">
			<%= link_to "What's MAMETRA", abouts_path %>
		</div>
		<div class="social">
			<%= link_to "ONLINE STORE", "http://mametra.shop-pro.jp/?mode=srh&cid=&keyword=", :target=>["_blank"] %>
			<%= link_to "Twitter", "https://twitter.com/mameused", :target=>["_blank"] %>
			<%= link_to "Instagram", "https://www.instagram.com/explore/locations/806413641/mametrakitchen/", :target=>["_blank"] %>
		</div>
		<%= link_to root_path do %>
			<%= image_tag 'mametra_logo.jpg', class: "logo" %>
		<% end %>
	</header>
	<!-- /header -->

    <%= yield %>
  </body>
</html>