config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }

  namespace :admin do

    resources :homes, :only => [:index]

    resources :products, :only => [:index, :new, :edit, :create, :update, :destroy] do
      patch :toggle_statuss
    end
    get 'products/:gender' => 'products#show', as: 'products_show'

    resources :arts, :only => [:index, :new, :edit, :create, :update, :destroy]

    resources :genres, :only => [:show]

  	resources :snaps, :only => [:index, :new, :edit, :create, :update, :destroy] do
  		resources :items, :only => [:create, :update, :destroy]
      resources :snap_images, :only => [:create, :update, :destroy]
  	end
  end

  resources :homes, :only => [:index]

  resources :abouts, :only => [:index]

  resources :products, :only => [:index]
  get 'products/:gender' => 'products#show', as: 'products_show'

  resources :snaps, :only => [:index]

  resources :delis, :only => [:index]

  resources :genres, :only => [:show]

  resources :arts, :only => [:index]

 	get 'contacts' => 'contacts#index'
	post 'contacts/confirm' => 'contacts#confirm'
	post 'contacts/thanks' => 'contacts#thanks'

	root 'homes#index'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/art.rb
class Art < ApplicationRecord

	extend Refile::Attachment
	attr_accessor :art_image_id
	has_many :art_images, inverse_of: :art, dependent: :destroy
	accepts_attachments_for :art_images, attachment: :image

	validates :event_name, presence: true
	validates :artist_name, presence: true
	validates :start_date, presence: true
	validates :end_date, presence: true
	validates :event_info, presence: true
end

app/models/art_image.rb
class ArtImage < ApplicationRecord
	belongs_to :art, optional: true, inverse_of: :art_images
	attachment :image
end

app/models/contact.rb
class Contact < include ActiveModel::Model
 
  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
end

app/models/deli.rb
class Deli < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items, inverse_of: :genre
	accepts_nested_attributes_for :items, allow_destroy: true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :genre , optional: true, inverse_of: :items
	belongs_to :snap , optional: true, inverse_of: :items

end

app/models/product.rb
class Product < ApplicationRecord
	has_many :product_images, dependent: :destroy
	accepts_attachments_for :product_images, attachment: :image

	enum statuss: { 販売中: 0, SOLDOUT: 1 }

	scope :get_by_gender, ->(gender) {
	where(gender: gender)
	}

	validates :product_name, presence: true
	validates :price, presence: true
	validates :gender, presence: true
	validates :size, presence: true

  def toggle_statuss!
    if 販売中?
      SOLDOUT!
    else
      販売中!
    end
  end
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
	belongs_to :product
	attachment :image
end

app/models/snap.rb
class Snap < ApplicationRecord
	 attr_accessor :genre_id
	 attr_accessor :item_name
	has_many :items, inverse_of: :snap, dependent: :destroy
        accepts_nested_attributes_for :items, allow_destroy: true

	extend Refile::Attachment
	attr_accessor :snap_image_id
	has_many :snap_images, inverse_of: :snap, dependent: :destroy
	accepts_attachments_for :snap_images, attachment: :image

end

app/models/snap_image.rb
class SnapImage < ApplicationRecord
	belongs_to :snap, optional: true, inverse_of: :snap_images
	attachment :image
end

app/controllers/admin/arts_controller.rb
class Admin::ArtsController < ApplicationController

	layout 'application.html 2'
	before_action :authenticate_admin!
	before_action :params_art, only:[:index, :update, :edit, :destroy]
	def index
		@arts = Art.all.reverse_order
	end

	def update
    	if @art.update(art_params)
    		redirect_to admin_arts_path
    	else
    		render :edit
    	end
	end

	def edit
	end

	def new
		@art = Art.new
		@art.art_images.build
	end

	def create
		@art = Art.new(art_params)
		if @art.save
			redirect_to admin_arts_path
		else
			render :new
		end
	end

	def destroy
		@art.destroy
		redirect_to admin_arts_path
 	end

	private

	def params_art
		@art = Art.find_by(id: params[:id])
	end

	def art_params
	  params.require(:art).permit(:id, :event_name, :artist_name, :start_date, :end_date, :event_info, art_images_images: [])
	end

end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
	def index
		@arts = Art.all.reverse_order
	end

	private

	def art_params
		params.require(:art).permit(:id, :event_name, :artist_name, :start_date, :end_date, :event_indo, art_images_images: [])
	end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admin/arts_helper.rb
module Admin::ArtsHelper
end

app/helpers/artimages_helper.rb
module ArtimagesHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/delis_helper.rb
module DelisHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/snapimages_helper.rb
module SnapimagesHelper
end

app/helpers/snaps_helper.rb
module SnapsHelper
end

app/views/admin/arts/edit.html.erb
<div class="panel panel-default container", style="margin-top: 70px;" >
	<div class="panel-body" >
		<%= form_for(@art, url: admin_arts_path, html: {class: 'form-horizontal'}) do |f| %>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Event Name</label>
				<div class="col-sm-10">
					<%= f.text_field :event_name, id:"InputText", class:"form-control", placeholder:"イベント名を入力して下さい。" %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Artist Name</label>
				<div class="col-sm-10">
					<%= f.text_field :artist_name, id:"InputText", class:"form-control", placeholder:"アーティスト名を入力して下さい。" %>
				</div>
			</div>
			<div class="form-group" id="datepicker-daterange">
				<label class="col-sm-2 control-label">Start ~ End</label>
				<div class="col-sm-9 form-inline">
					<div class="input-daterange input-group" id="datepicker">
						<%= f.date_field :start_date, id:"InputText", class:"form-control" %>
						<span class="input-group-addon">to</span>
						<%= f.date_field :end_date, id:"InputText", class:"form-control" %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputFile">Art Image</label>
				<div class="col-sm-10">
					<%= f.attachment_field :art_images_images, id:"InputFile", multiple: true %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputTextarea">Art Info</label>
				<div class="col-sm-10">
					<%= f.text_area :event_info, id:"InputTextarea", class:"form-control", placeholder:"イベント情報を入力してください。", rows:"8" %>
				</div>
			</div>
			<%= f.submit '編集する', class:"btn btn-primary center-block" %>
		<% end %>
	</div>
	<div class="panel-footer" >
	</div>
</div>

app/views/admin/arts/index.html.erb
<div class="section-content">
	<div class="section-main2">
		<% @arts.each do |art| %>
		<div class="art-content">
			<%#= link_to "編集", edit_admin_art_path(art), class:"btn btn-primary btn-xs" %>
			<%= link_to "削除", admin_art_path(art), method: :delete, class:"btn btn-danger btn-xs", "data-confirm" => "本当に削除しますか？" %>
			<div class="event-info">
				<p class="event-period"><%= art.start_date %> ~ <%= art.end_date %></p>
				<h2 class="event-name"><%= art.event_name %></h2>
				<h3 class="artist-name"><%= art.artist_name %></h3>
				<%= simple_format(art.event_info, :class => "event-text") %>
			</div>
			<div>
				<ul class="event-photo">
					<% art.art_images.each do |image| %>
						<%= attachment_image_tag image, :image, :fill, 600, 420 %>
					<% end %>
				</ul>
			</div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/arts/new.html.erb
<div class="panel panel-default container", style="margin-top: 70px;" >
	<div class="panel-body" >
		<%= form_for(@art, url: admin_arts_path, html: {class: 'form-horizontal'}) do |f| %>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Event Name</label>
				<div class="col-sm-10">
					<%= f.text_field :event_name, id:"InputText", class:"form-control", placeholder:"イベント名を入力して下さい。" %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputText">Artist Name</label>
				<div class="col-sm-10">
					<%= f.text_field :artist_name, id:"InputText", class:"form-control", placeholder:"アーティスト名を入力して下さい。" %>
				</div>
			</div>
			<div class="form-group" id="datepicker-daterange">
				<label class="col-sm-2 control-label">Start ~ End</label>
				<div class="col-sm-9 form-inline">
					<div class="input-daterange input-group" id="datepicker">
						<%= f.date_field :start_date, id:"InputText", class:"form-control" %>
						<span class="input-group-addon">to</span>
						<%= f.date_field :end_date, id:"InputText", class:"form-control" %>
					</div>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputFile">Art Image</label>
				<div class="col-sm-10">
					<%= f.attachment_field :art_images_images, id:"InputFile", multiple: true %>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label" for="InputTextarea">Art Info</label>
				<div class="col-sm-10">
					<%= f.text_area :event_info, id:"InputTextarea", class:"form-control", placeholder:"イベント情報を入力してください。", rows:"8" %>
				</div>
			</div>
			<%= f.submit '作成する', class:"btn btn-primary center-block" %>
		<% end %>
	</div>
	<div class="panel-footer" >
	</div>
</div>

app/views/arts/index.html.erb
<section id="home" class="home open">
</section>
<section id="used&clothing" class="used&clothing open">
	<%= link_to snaps_path do %>
	<h1>SNAP SHOT</h1>
	<% end %>
	<div class="section-content">
	</div>
</section>
<section id="deli&cafe" class="deli&cafe open">
	<%= link_to delis_path do %>
	<h1>DELI CAFE</h1>
	<% end %>
	<div class="section-content">
	</div>
</section>
<section id="artspace" class="artspace open active">
	<%= link_to arts_path, style: "color: #fff;" do %>
	<h1>ART SPACE</h1>
	<% end %>
	<div class="section-content">
		<div class="section-main">
			<h2>ArtSpace Infomation</h2>
			<% @arts.each do |art| %>
			<div class="art-content">
				<div class="event-info">
					<p class="event-period">期間：<%= art.start_date %>~<%= art.end_date %></p>
					<h2 class="event-name"><%= art.event_name %></h2>
					<h3 class="artist-name">Artist "<%= art.artist_name %>"</h3>
					<%= simple_format(art.event_info, :class => "event-text") %>
				</div>
				<div>
					<ul class="event-photo">
						<% art.art_images.each do |image| %>
							<%= attachment_image_tag image, :image %>
						<% end %>
					</ul>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</section>